const tintColorLight = "#0a7ea4";
const tintColorDark = "#fff";

export const Colors = {
  light: {
    text: "#11181C",
    tint: tintColorLight,
    icon: "#687076",
    tabIconDefault: "#687076",
    tabIconSelected: tintColorLight,
    background: "#FFFFFF",
    foreground: "#0A0A0A",
    card: "#FFFFFF",
    cardForeground: "#0A0A0A",
    popover: "#FFFFFF",
    popoverForeground: "#0A0A0A",
    primary: "#E11D48",
    primaryForeground: "#FDF2F2",
    secondary: "#F5F5F5",
    secondaryForeground: "#171717",
    muted: "#F5F5F5",
    mutedForeground: "#737373",
    accent: "#F5F5F5",
    accentForeground: "#171717",
    destructive: "#E11D48",
    destructiveForeground: "#FAFAFA",
    border: "#E5E5E5",
    input: "#E5E5E5",
    ring: "#E11D48",
  },
  dark: {
    text: "#ECEDEE",
    tint: tintColorDark,
    icon: "#9BA1A6",
    tabIconDefault: "#9BA1A6",
    tabIconSelected: tintColorDark,
    background: "#0A0A0A",
    foreground: "#FAFAFA",
    card: "#0A0A0A",
    cardForeground: "#FAFAFA",
    popover: "#0A0A0A",
    popoverForeground: "#FAFAFA",
    primary: "#E11D48",
    primaryForeground: "#FDF2F2",
    secondary: "#262626",
    secondaryForeground: "#FAFAFA",
    muted: "#262626",
    mutedForeground: "#A3A3A3",
    accent: "#262626",
    accentForeground: "#FAFAFA",
    destructive: "#7F1D1D",
    destructiveForeground: "#FAFAFA",
    border: "#262626",
    input: "#262626",
    ring: "#E11D48",
  },
  own: tintColorLight,
  ownLight: "#54C1D6",
};
